from asir.composites.perceptual import FullPerceptualDescription
from asir.composites.scene import SceneWithHistory
from asir.composites.strategy import GenerateFullStrategy
from asir.composites.translation import comp_strategy_to_dsp_params
